---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cop-data-api-spec-ingress
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: cop-data-api-spec-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.HOSTNAME}}
    secretName: cop-data-api-spec-tls
