---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cop-data-api-spec-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: {{.HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: cop-data-api-spec-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.HOSTNAME}}
    secretName: cop-data-api-spec-cmio
